### ISSUE TITLE
Better support for large port ranges on ingress

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#10]
as i understand it, the current implementation creates 1 filter for each port in declared port range in the ingress case.

unfortunately, it's often the case with media streams that they may be assigned across a large range of ports (eg., in my current testing suite, RTP traffic gets randomly assigned to UDP ports 10000-35000 on the server)

so we need a better solution than the current one for ingress.

i'll note that it would be acceptable (although not ideal) to shape all UDP ports on ingress, as long as it's still possible to shape individual TCP ports on ingress as well.

**Comment by yassen-itlabs** [comment]
TC for all UDP ports is definitely achievable. Let's do that until we have a real solution.

The issue here is the ematch filter doesn't work for the ifb device (have no idea why). Wrote to the LARTC list and the response was that it should work. I'll make another round of tests to see why my first results showed it didn't.

**Comment by yassen-itlabs** [comment]
Finally, it seems that my initial experiments that showed the ematch filtering not working for an ifb device were somehow incorrect (don't know how/why). The filter works and we reverted the filter-building logic to use that instead of a series of single u32-based filters. Thus  24d1069 resolves this. Closing.
