### ISSUE TITLE
Migrate README and CHANGES from .rst to .md

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#19]
.md is the defacto markup for Github files like a README. is there some compelling reason to be using .rst?

**Comment by yassen-itlabs** [comment]
yep, I was careful choosing the format. I envision maintaining a real read-the-docs site generating it out of the repository using Spinx (www.sphinx-doc.org). Spinx is the standard in documenting python projects and Spinx is .rst. So let's keep the README in sync with the other documentation.

For the future, I think we should have a shorter README (now it looks more like a manual, which is good, because there is no other manual, but when we have, we should move all that to the manual). I hope you agree.

**Comment by thehunmonkgroup** [comment]
Ok, that works for me, and I've now at least figured out why my markdown wasn't working in the README :P
